// Mocks generated by Mockito 5.4.4 from annotations
// in odoo_delivery_app/test/unit_test/Picking/create_picking_unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:odoo_delivery_app/NavBars/Pickings/CreateNewPicking/models/Hive/pending_creates.dart'
    as _i12;
import 'package:odoo_delivery_app/NavBars/Pickings/CreateNewPicking/models/operation_type.dart'
    as _i8;
import 'package:odoo_delivery_app/NavBars/Pickings/CreateNewPicking/models/partner.dart'
    as _i6;
import 'package:odoo_delivery_app/NavBars/Pickings/CreateNewPicking/models/product.dart'
    as _i5;
import 'package:odoo_delivery_app/NavBars/Pickings/CreateNewPicking/models/user.dart'
    as _i7;
import 'package:odoo_delivery_app/NavBars/Pickings/CreateNewPicking/services/odoo_create_picking_service.dart'
    as _i2;
import 'package:odoo_delivery_app/NavBars/Pickings/PickingFormPage/models/operation_type.dart'
    as _i18;
import 'package:odoo_delivery_app/NavBars/Pickings/PickingFormPage/models/partner.dart'
    as _i16;
import 'package:odoo_delivery_app/NavBars/Pickings/PickingFormPage/models/partner_details.dart'
    as _i20;
import 'package:odoo_delivery_app/NavBars/Pickings/PickingFormPage/models/pending_updates.dart'
    as _i11;
import 'package:odoo_delivery_app/NavBars/Pickings/PickingFormPage/models/pending_validation.dart'
    as _i10;
import 'package:odoo_delivery_app/NavBars/Pickings/PickingFormPage/models/picking_form.dart'
    as _i14;
import 'package:odoo_delivery_app/NavBars/Pickings/PickingFormPage/models/product.dart'
    as _i15;
import 'package:odoo_delivery_app/NavBars/Pickings/PickingFormPage/models/product_update.dart'
    as _i13;
import 'package:odoo_delivery_app/NavBars/Pickings/PickingFormPage/models/stock_move.dart'
    as _i19;
import 'package:odoo_delivery_app/NavBars/Pickings/PickingFormPage/models/user.dart'
    as _i17;
import 'package:odoo_delivery_app/NavBars/Pickings/PickingFormPage/services/hive_service.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [OdooCreatePickingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOdooCreatePickingService extends _i1.Mock
    implements _i2.OdooCreatePickingService {
  MockOdooCreatePickingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get url => (super.noSuchMethod(
        Invocation.getter(#url),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#url),
        ),
      ) as String);

  @override
  _i4.Future<bool> checkNetworkConnectivity() => (super.noSuchMethod(
        Invocation.method(
          #checkNetworkConnectivity,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<List<_i5.ProductModel>> loadProducts() => (super.noSuchMethod(
        Invocation.method(
          #loadProducts,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.ProductModel>>.value(<_i5.ProductModel>[]),
      ) as _i4.Future<List<_i5.ProductModel>>);

  @override
  _i4.Future<List<_i6.PartnerModel>> loadPartners() => (super.noSuchMethod(
        Invocation.method(
          #loadPartners,
          [],
        ),
        returnValue:
            _i4.Future<List<_i6.PartnerModel>>.value(<_i6.PartnerModel>[]),
      ) as _i4.Future<List<_i6.PartnerModel>>);

  @override
  _i4.Future<List<_i7.UserModel>> loadUsers() => (super.noSuchMethod(
        Invocation.method(
          #loadUsers,
          [],
        ),
        returnValue: _i4.Future<List<_i7.UserModel>>.value(<_i7.UserModel>[]),
      ) as _i4.Future<List<_i7.UserModel>>);

  @override
  _i4.Future<List<_i8.OperationTypeModel>> loadOperationTypes() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadOperationTypes,
          [],
        ),
        returnValue: _i4.Future<List<_i8.OperationTypeModel>>.value(
            <_i8.OperationTypeModel>[]),
      ) as _i4.Future<List<_i8.OperationTypeModel>>);

  @override
  _i4.Future<int> createPicking({
    required int? partnerId,
    required int? operationTypeId,
    required String? scheduledDate,
    String? origin,
    required String? moveType,
    int? userId,
    String? note,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPicking,
          [],
          {
            #partnerId: partnerId,
            #operationTypeId: operationTypeId,
            #scheduledDate: scheduledDate,
            #origin: origin,
            #moveType: moveType,
            #userId: userId,
            #note: note,
          },
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<Map<String, dynamic>> getPickingLocations(int? pickingId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPickingLocations,
          [pickingId],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> createStockMove({
    required String? name,
    required int? productId,
    required double? productUomQty,
    required int? productUomId,
    required int? pickingId,
    required int? locationId,
    required int? locationDestId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStockMove,
          [],
          {
            #name: name,
            #productId: productId,
            #productUomQty: productUomQty,
            #productUomId: productUomId,
            #pickingId: pickingId,
            #locationId: locationId,
            #locationDestId: locationDestId,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>?> getNewPickingDetails(int? pickingId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNewPickingDetails,
          [pickingId],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);
}

/// A class which mocks [HiveService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHiveService extends _i1.Mock implements _i9.HiveService {
  MockHiveService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveTotalCount(int? count) => (super.noSuchMethod(
        Invocation.method(
          #saveTotalCount,
          [count],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  int getTotalCount() => (super.noSuchMethod(
        Invocation.method(
          #getTotalCount,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i4.Future<void> savePendingValidation(
    int? pickingId,
    Map<String, dynamic>? pickingData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePendingValidation,
          [
            pickingId,
            pickingData,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i10.PendingValidation>> getPendingValidations() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingValidations,
          [],
        ),
        returnValue: _i4.Future<List<_i10.PendingValidation>>.value(
            <_i10.PendingValidation>[]),
      ) as _i4.Future<List<_i10.PendingValidation>>);

  @override
  _i4.Future<void> clearPendingValidation(int? pickingId) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearPendingValidation,
          [pickingId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllPendingValidations() => (super.noSuchMethod(
        Invocation.method(
          #clearAllPendingValidations,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> savePendingCancellation(
    int? pickingId,
    Map<String, dynamic>? pickingData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePendingCancellation,
          [
            pickingId,
            pickingData,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i10.PendingValidation>> getPendingCancellations() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingCancellations,
          [],
        ),
        returnValue: _i4.Future<List<_i10.PendingValidation>>.value(
            <_i10.PendingValidation>[]),
      ) as _i4.Future<List<_i10.PendingValidation>>);

  @override
  _i4.Future<void> clearPendingCancellation(int? pickingId) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearPendingCancellation,
          [pickingId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllPendingCancellations() => (super.noSuchMethod(
        Invocation.method(
          #clearAllPendingCancellations,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> savePendingUpdates(
    int? pickingId,
    Map<String, dynamic>? pickingData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePendingUpdates,
          [
            pickingId,
            pickingData,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i11.PendingUpdates>> getPendingUpdates() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingUpdates,
          [],
        ),
        returnValue: _i4.Future<List<_i11.PendingUpdates>>.value(
            <_i11.PendingUpdates>[]),
      ) as _i4.Future<List<_i11.PendingUpdates>>);

  @override
  _i4.Future<void> clearPendingUpdates(int? pickingId) => (super.noSuchMethod(
        Invocation.method(
          #clearPendingUpdates,
          [pickingId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllPendingUpdates() => (super.noSuchMethod(
        Invocation.method(
          #clearAllPendingUpdates,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> savePendingCreates(Map<String, dynamic>? pickingData) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePendingCreates,
          [pickingData],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i12.PendingCreates>> getPendingCreates() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingCreates,
          [],
        ),
        returnValue: _i4.Future<List<_i12.PendingCreates>>.value(
            <_i12.PendingCreates>[]),
      ) as _i4.Future<List<_i12.PendingCreates>>);

  @override
  _i4.Future<void> clearPendingCreates(int? pickingId) => (super.noSuchMethod(
        Invocation.method(
          #clearPendingCreates,
          [pickingId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllPendingCreates() => (super.noSuchMethod(
        Invocation.method(
          #clearAllPendingCreates,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> savePendingProductUpdates(
    int? localId,
    Map<String, dynamic>? productData,
    String? PickingName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePendingProductUpdates,
          [
            localId,
            productData,
            PickingName,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i13.ProductUpdates>> getPendingProductUpdates() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingProductUpdates,
          [],
        ),
        returnValue: _i4.Future<List<_i13.ProductUpdates>>.value(
            <_i13.ProductUpdates>[]),
      ) as _i4.Future<List<_i13.ProductUpdates>>);

  @override
  _i4.Future<void> clearPendingProductUpdates(int? pickingId) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearPendingProductUpdates,
          [pickingId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllPendingProductUpdates() => (super.noSuchMethod(
        Invocation.method(
          #clearAllPendingProductUpdates,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> savePickings(List<Map<String, dynamic>>? pickings) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePickings,
          [pickings],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i14.PickingForm>> getPickings() => (super.noSuchMethod(
        Invocation.method(
          #getPickings,
          [],
        ),
        returnValue:
            _i4.Future<List<_i14.PickingForm>>.value(<_i14.PickingForm>[]),
      ) as _i4.Future<List<_i14.PickingForm>>);

  @override
  _i4.Future<void> saveReturnPickings(List<Map<String, dynamic>>? pickings) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveReturnPickings,
          [pickings],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i14.PickingForm>> getReturnPickings() => (super.noSuchMethod(
        Invocation.method(
          #getReturnPickings,
          [],
        ),
        returnValue:
            _i4.Future<List<_i14.PickingForm>>.value(<_i14.PickingForm>[]),
      ) as _i4.Future<List<_i14.PickingForm>>);

  @override
  _i4.Future<_i14.PickingForm?> getPickingById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getPickingById,
          [id],
        ),
        returnValue: _i4.Future<_i14.PickingForm?>.value(),
      ) as _i4.Future<_i14.PickingForm?>);

  @override
  _i4.Future<void> saveProducts(List<Map<String, dynamic>>? products) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveProducts,
          [products],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i15.Product>> getProducts() => (super.noSuchMethod(
        Invocation.method(
          #getProducts,
          [],
        ),
        returnValue: _i4.Future<List<_i15.Product>>.value(<_i15.Product>[]),
      ) as _i4.Future<List<_i15.Product>>);

  @override
  _i4.Future<void> savePartners(List<Map<String, dynamic>>? partners) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePartners,
          [partners],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i16.Partner>> getPartners() => (super.noSuchMethod(
        Invocation.method(
          #getPartners,
          [],
        ),
        returnValue: _i4.Future<List<_i16.Partner>>.value(<_i16.Partner>[]),
      ) as _i4.Future<List<_i16.Partner>>);

  @override
  _i4.Future<void> saveUsers(List<Map<String, dynamic>>? users) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUsers,
          [users],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i17.User>> getUsers() => (super.noSuchMethod(
        Invocation.method(
          #getUsers,
          [],
        ),
        returnValue: _i4.Future<List<_i17.User>>.value(<_i17.User>[]),
      ) as _i4.Future<List<_i17.User>>);

  @override
  _i4.Future<void> saveOperationTypes(
          List<Map<String, dynamic>>? operationTypes) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveOperationTypes,
          [operationTypes],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i18.OperationType>> getOperationTypes() =>
      (super.noSuchMethod(
        Invocation.method(
          #getOperationTypes,
          [],
        ),
        returnValue:
            _i4.Future<List<_i18.OperationType>>.value(<_i18.OperationType>[]),
      ) as _i4.Future<List<_i18.OperationType>>);

  @override
  _i4.Future<void> saveStockMoves(List<Map<String, dynamic>>? moves) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveStockMoves,
          [moves],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i19.StockMove>> getStockMoves({int? pickingId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStockMoves,
          [],
          {#pickingId: pickingId},
        ),
        returnValue: _i4.Future<List<_i19.StockMove>>.value(<_i19.StockMove>[]),
      ) as _i4.Future<List<_i19.StockMove>>);

  @override
  _i4.Future<void> savePartnerDetails(_i20.PartnerDetails? details) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePartnerDetails,
          [details],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i20.PartnerDetails?> getPartnerDetails(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPartnerDetails,
          [id],
        ),
        returnValue: _i4.Future<_i20.PartnerDetails?>.value(),
      ) as _i4.Future<_i20.PartnerDetails?>);

  @override
  _i4.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
