name: Feature Request
description: Suggest a new feature or improvement
title: "[FEATURE] "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature!
        Please fill out the details below to help us understand your idea clearly.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Clearly explain the feature you are requesting.
      placeholder: Describe the feature in detail...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Explain the current limitation or issue...
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: How will this feature help users?
      placeholder: Example - This helps users automate...
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add screenshots, mockups, or references if any.
      placeholder: Drag and drop images or paste links here...
