// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:odoo_delivery_app/Dashboard/models/profile.dart';
import 'package:odoo_delivery_app/NavBars/Pickings/CreateNewPicking/models/Hive/pending_creates.dart';
import 'package:odoo_delivery_app/NavBars/Pickings/PickingFormPage/models/move_line.dart';
import 'package:odoo_delivery_app/NavBars/Pickings/PickingFormPage/models/operation_type.dart';
import 'package:odoo_delivery_app/NavBars/Pickings/PickingFormPage/models/partner.dart';
import 'package:odoo_delivery_app/NavBars/Pickings/PickingFormPage/models/partner_details.dart';
import 'package:odoo_delivery_app/NavBars/Pickings/PickingFormPage/models/pending_updates.dart';
import 'package:odoo_delivery_app/NavBars/Pickings/PickingFormPage/models/pending_validation.dart';
import 'package:odoo_delivery_app/NavBars/Pickings/PickingFormPage/models/picking_form.dart';
import 'package:odoo_delivery_app/NavBars/Pickings/PickingFormPage/models/product.dart';
import 'package:odoo_delivery_app/NavBars/Pickings/PickingFormPage/models/product_update.dart';
import 'package:odoo_delivery_app/NavBars/Pickings/PickingFormPage/models/return_picking.dart';
import 'package:odoo_delivery_app/NavBars/Pickings/PickingFormPage/models/stock_move.dart';
import 'package:odoo_delivery_app/NavBars/Pickings/PickingFormPage/models/user.dart';
import 'package:odoo_delivery_app/NavBars/Pickings/PickingListPage/models/picking_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(MoveLineAdapter());
    registerAdapter(OperationTypeAdapter());
    registerAdapter(PartnerAdapter());
    registerAdapter(PartnerDetailsAdapter());
    registerAdapter(PendingCreatesAdapter());
    registerAdapter(PendingUpdatesAdapter());
    registerAdapter(PendingValidationAdapter());
    registerAdapter(PickingAdapter());
    registerAdapter(PickingFormAdapter());
    registerAdapter(ProductAdapter());
    registerAdapter(ProductUpdatesAdapter());
    registerAdapter(ProfileAdapter());
    registerAdapter(ReturnPickingAdapter());
    registerAdapter(StockMoveAdapter());
    registerAdapter(UserAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(MoveLineAdapter());
    registerAdapter(OperationTypeAdapter());
    registerAdapter(PartnerAdapter());
    registerAdapter(PartnerDetailsAdapter());
    registerAdapter(PendingCreatesAdapter());
    registerAdapter(PendingUpdatesAdapter());
    registerAdapter(PendingValidationAdapter());
    registerAdapter(PickingAdapter());
    registerAdapter(PickingFormAdapter());
    registerAdapter(ProductAdapter());
    registerAdapter(ProductUpdatesAdapter());
    registerAdapter(ProfileAdapter());
    registerAdapter(ReturnPickingAdapter());
    registerAdapter(StockMoveAdapter());
    registerAdapter(UserAdapter());
  }
}
