// Mocks generated by Mockito 5.4.4 from annotations
// in odoo_delivery_app/test/unit_test/Login/credential_unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:odoo_delivery_app/LoginPage/models/auth_model.dart' as _i4;
import 'package:odoo_delivery_app/LoginPage/models/session_model.dart' as _i5;
import 'package:odoo_delivery_app/LoginPage/services/app_install_check.dart'
    as _i6;
import 'package:odoo_delivery_app/LoginPage/services/auth_service.dart' as _i2;
import 'package:odoo_delivery_app/LoginPage/services/storage_service.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i2.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.AuthenticationResult> authenticateWithBiometrics() =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticateWithBiometrics,
          [],
        ),
        returnValue: _i3.Future<_i4.AuthenticationResult>.value(
            _i4.AuthenticationResult.success),
      ) as _i3.Future<_i4.AuthenticationResult>);

  @override
  int parseMajorVersion(String? serverVersion) => (super.noSuchMethod(
        Invocation.method(
          #parseMajorVersion,
          [serverVersion],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i3.Future<Map<String, dynamic>> getSessionInfo(
    String? url,
    String? sessionId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessionInfo,
          [
            url,
            sessionId,
          ],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<dynamic> callKwWithSession({
    required String? url,
    required String? sessionId,
    required Map<String, dynamic>? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #callKwWithSession,
          [],
          {
            #url: url,
            #sessionId: sessionId,
            #payload: payload,
          },
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<_i5.SessionModel?> authenticateOdoo({
    required String? url,
    required String? database,
    required String? username,
    required String? password,
    dynamic sessionId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticateOdoo,
          [],
          {
            #url: url,
            #database: database,
            #username: username,
            #password: password,
            #sessionId: sessionId,
          },
        ),
        returnValue: _i3.Future<_i5.SessionModel?>.value(),
      ) as _i3.Future<_i5.SessionModel?>);
}

/// A class which mocks [AppInstallCheck].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppInstallCheck extends _i1.Mock implements _i6.AppInstallCheck {
  MockAppInstallCheck() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> isModuleInstalled(String? moduleName) => (super.noSuchMethod(
        Invocation.method(
          #isModuleInstalled,
          [moduleName],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> checkRequiredModules() => (super.noSuchMethod(
        Invocation.method(
          #checkRequiredModules,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i7.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveSession(_i5.SessionModel? session) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSession,
          [session],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveLoginState({
    required bool? isLoggedIn,
    required String? database,
    required String? url,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveLoginState,
          [],
          {
            #isLoggedIn: isLoggedIn,
            #database: database,
            #url: url,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> getLoginStatus() => (super.noSuchMethod(
        Invocation.method(
          #getLoginStatus,
          [],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);
}
